[package]
name = "bors"
version = "0.1.0"
edition = "2021"

authors = ["Gagandeep Singh <totsteps.gs@gmail.com>"]
repository = "https://github.com/totsteps/bors"
readme = "README.md"
description = "TBD"
license = "TBD"

[dependencies]
axum = "0.5.17"
tokio = { version = "1.21.2", features = ["full"] }
